import builtins from "builtin-modules";
import esbuild from "esbuild";
import esbuildSvelte from "esbuild-svelte";
import fs from "fs";
import path from "path";
import process from "process";
import { sveltePreprocess } from "svelte-preprocess";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const rebuildPlugin = {
	name: "rebuild-handler",
	setup(build) {
		build.onEnd(async () => {
			try {
				// Copy manifest.json
				await fs.promises.copyFile(
					path.join(path.resolve(), "manifest.json"),
					path.join(path.resolve(), "dist", "manifest.json")
				);
				
				// Copy compiled scripts folder
				const scriptsDir = path.join(path.resolve(), "scripts");
				const distScriptsDir = path.join(path.resolve(), "dist", "scripts");
				
				// Create dist/scripts directory if it doesn't exist
				await fs.promises.mkdir(distScriptsDir, { recursive: true });
				
				// Copy all compiled script files (TypeScript compiles to .js)
				const files = await fs.promises.readdir(scriptsDir);
				for (const file of files) {
					if (file.endsWith('.js')) {
						await fs.promises.copyFile(
							path.join(scriptsDir, file),
							path.join(distScriptsDir, file)
						);
					}
				}
			} catch (err) {
				console.error('Error copying files:', err);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: prod,
	plugins: [
		rebuildPlugin,
		esbuildSvelte({
			compilerOptions: {
				css: "injected",
			},
			preprocess: sveltePreprocess(),
		}),
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
